config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  get '/splash', to: 'splashes#index'


  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root "splashes#index", as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show, :new] do
    resources :categories, only: [:new, :create, :show, :index, :destroy]
    resources :entities, only: [:new, :create, :index, :show, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_and_belongs_to_many :entities

  validates :name, :icon, presence: true

  def self.total_amount(user)
    total_amount = 0
    @categories = Category.where(author_id: user) || []
    @categories.each do |category|
      amount = category.entities.sum(:amount)
      total_amount += amount
    end
    total_amount
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(author_id: current_user.id).order(created_at: :desc) || []
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.includes(:entities).find(params[:id])
    @entities = @category.entities.order(created_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.author = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to authenticated_root_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to authenticated_root_path, notice: 'Category was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon).merge(author_id: current_user.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li class="category-list">
  <div class="img-container">
    <%= link_to  user_category_path( current_user, category) do %>
      <% def valid_image_url?(url) %>
        <% url.present? && url =~ /\Ahttps?:\/\/\S+\z/ %>
      <% end %>
      <% if valid_image_url?(category.icon) %>
        <%= image_tag category.icon, alt: 'My Image' %>
      <% else %>
        <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJcT7PQqrhP-fcTi2K3UTvx1CZMmLvFPvupUZivUCJMFDRsX4LxhTRuenl5VHpbhs7elI&usqp=CAU', alt: 'My Image' %>
      <% end %>
    <% end %>
  </div>
  <div class="details">
    <p><%= link_to  category.name.capitalize, user_category_path( current_user, category) %></p>
    <p class="date"><%=  category.created_at.strftime("%d %b %Y") %></p>
  </div>
  <div class="amount">
    <p>$<%= category.entities.sum(:amount)%></p>
    
    <% if can? :destroy, category %>
      <%= button_to user_category_path(current_user, category),
        method: :delete,
        data: { confirm: 'Are you sure you want to delete this category?' },
        title: "Delete #{category.name.capitalize} category" do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    <% end %>
    
  </div>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: category, url: user_categories_path) do |form| %>
  <div class="input-container">
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, autofocus: true,  placeholder: "Name", required: true  %>
    </div>

    <div>
      <%= form.label :icon %>
      <%= form.text_field :icon, placeholder: "Icon URL", required: true  %>
    </div>
  </div>

  <div class="btn">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="total">
  <p>Total amount:</p>
  <p>$<%= Category.total_amount(current_user.id) %></p>
</div>

<% if @categories.any? %>
  <div id="categories">
    <% @categories.each do |category| %>
      <ul><%= render category %></ul>
    <% end %>
  </div>
<% end %>


<div class="btn">
  <%= link_to "New category", new_user_category_path(current_user) %>
</div>

app/views/categories/new.html.erb
<div class="category-form">
  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<%= render @category %>

<div class="category-transactions">
<h4 class="transactions-title">Transactions</h4>
  <% if @entities.empty? %>
    <p class="empty-transaction">No transactions available.</p>
  <% else %>
      <div class="transaction-details-container">
        <% @entities.each do |entity| %>
          <% if can? :read,  entity%>
            <div class="transaction-details">
              <p><%= entity.name.capitalize%></p>
              <p>$<%= entity.amount%></p>
            </div>
          <% end %>
        <% end %>
      </div>
  <% end %>
</div>


<div class="btn">
  <%= link_to "Add transaction", new_user_entity_path(current_user) %>
</div>